server:
  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    hostname: prometheus.167.254.190.2.nip.io
  resources:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 3
      memory: 4Gi

  extraScrapeConfigs:
    - job_name: 'alarm-etl-job'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: [ 'alarm-spk.ndl:8080' ]
    - job_name: 'cadvisor'
      static_configs:
        - targets: [ 'cadvisor.monitor:8080' ]
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: [ 'kube-state-metrics.monitor:8080' ]
    - job_name: 'node-exporters'
      static_configs:
        - targets: [ 'node-exporter-prometheus-node-exporter.monitor:9100' ]
    - job_name: 'kafka-jxm-exporter'
      static_configs:
        - targets: [ 'kafka-jmx-metrics.kafka:5556' ]
    - job_name: 'kafka-exporter'
      static_configs:
        - targets: [ 'kafka-exporter-prometheus-kafka-exporter.kafka:9308' ]
    - job_name: 'elasticsearch-exporter'
      static_configs:
        - targets: [ 'elasticsearch-metrics.elastic:9114' ]
    - job_name: 'cassandra-http-exporter'
      static_configs:
        - targets: [ 'cassandra.cassandra:8080' ]
    - job_name: 'cassandra-jxm-exporter'
      static_configs:
        - targets: [ 'cassandra.cassandra:5555' ]

  persistence:
    enabled: true
    storageClass: longhorn
    size: 20Gi